WebApps/MemberAdmin/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Archymeta.Web.MembershipPlus.AppLayer;
using MemberAdminMvc5.Models;
using MemberAdminMvc5.SignalRHubs;

namespace MemberAdminMvc5.Controllers
{
    public class ContactsController : Controller
    {
        private async Task PopulateTypes(ContactsQueryOpts m)
        {
            List<ContactType> l = new List<ContactType>();
            var types = await ContactContext.ListTypes();
            foreach (var type in types)
            {
                var t = new ContactType
                {
                    Id = type.ID,
                    Name = type.TypeName // map it to a more user friendly name later.
                };
                l.Add(t);
            }
            m.Types = l.ToArray();
        }

        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Search(int? typeId, bool? outgoing)
        {
            ViewBag.AppName = Startup.App.Name;
            var m = new ContactsQueryOpts
            {
                UserId = User.Identity.GetUserId(),
                TypeId = typeId == null ? -1 : typeId.Value,
                Outgoing = outgoing == null ? true : outgoing.Value
            };
            await PopulateTypes(m);
            return View(m);
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> GetMembers(string set, string qexpr, string prevlast, bool? outgoing)
        {
            var nhub = new NotificationHub();
            string data = await ContactContext.GetMembers(nhub.HubIdentity, User.Identity.GetUserId(), set, qexpr, prevlast, outgoing == null ? true : outgoing.Value);
            return Json(data);
        }
    }
}

WebApps/MemberAdmin/Controllers/GroupChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Archymeta.Web.MembershipPlus.AppLayer;
using MemberAdminMvc5.Models;

namespace MemberAdminMvc5.Controllers
{
    public class GroupChatController : BaseController
    {
        protected string HubId
        {
            get
            {
                if (_hubId == null)
                {
                    var hub = new SignalRHubs.GroupChatHub();
                    _hubId = hub.HubIdentity;
                }
                return _hubId;
            }
        }
        private string _hubId = null;

        protected int MaxInitMsgs
        {
            get
            {
                if (_maxMsgs.HasValue == false)
                {
                    string str = ConfigurationManager.AppSettings["MaxInitialChatMessages"];
                    int ival;
                    if (!string.IsNullOrEmpty(str) && int.TryParse(str, out ival))
                        _maxMsgs = ival;
                    else
                        _maxMsgs = 100;
                }
                return _maxMsgs.Value;
            }
        }
        private int? _maxMsgs = null;

        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Start()
        {
            var m = await GroupChatContext.ListChatRooms(User.Identity.GetUserId());
            return View(m);
        }

        [HttpGet]
        [Authorize]
        public async Task<dynamic> LoadRoomSummary(string id)
        {
            dynamic data = await GroupChatContext.LoadRoomSummary(HubId, id);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Authorize]
        public async Task<ActionResult> ChatRoom(string id, bool? seq)
        {
            var m = await GroupChatContext.LoadChatRoom(HubId, id, User.Identity.GetUserId(), MaxInitMsgs, !seq.HasValue || !seq.Value);
            if (m.RoomExists)
                return View(m);
            else
                return new HttpStatusCodeResult(404, "Not Found");
        }

        [HttpGet]
        [Authorize]
        public async Task<ActionResult> LoadMessages(string id, bool? seq)
        {
            var msgs = await GroupChatContext.LoadMessages(id, User.Identity.GetUserId(), MaxInitMsgs, !seq.HasValue || !seq.Value);
            return Json(msgs, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Subscribe(string id)
        {
            var s = await GroupChatContext.Subscribe(User.Identity.GetUserId(), id);
            return Json(s);
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> ChangeNotification(string id)
        {
            var s = await GroupChatContext.ChangeNotification(User.Identity.GetUserId(), id);
            return Json(s);
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Unsubscribe(string id)
        {
            var s = await GroupChatContext.Unsubscribe(User.Identity.GetUserId(), id);
            return Json(s);
        }

        [HttpGet]
        [Authorize]
        public async Task<ActionResult> ListConnectedMembers(string id)
        {
            return Json(await GroupChatContext.ListConnectedMembers(HubId, id), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Authorize]
        public ActionResult PrevMessages(string k, int? v)
        {
            TimeSpanValueKind kind = k != null ? (TimeSpanValueKind)Enum.Parse(typeof(TimeSpanValueKind), k) : TimeSpanValueKind.Hours;

            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult Search()
        {

            return View();
        }
    }
}

WebApps/MemberAdmin/Controllers/QueryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Threading;
using System.Security.Principal;
using Microsoft.IdentityModel;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using CryptoGateway.RDB.Data.MembershipPlus;
using Archymeta.Web.Security;
using Archymeta.Web.Security.Resources;
using Archymeta.Web.MembershipPlus.AppLayer;
using Archymeta.Web.MembershipPlus.AppLayer.Models;
using MemberAdminMvc5.Models;

namespace MemberAdminMvc5.Controllers
{
    [Authorize]
    public class QueryController : BaseController
    {
        [HttpGet]
        public ActionResult SearchMembers()
        {
            ViewBag.AppName = Startup.App.Name;
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> GetMembers(string set, string qexpr, string prevlast)
        {
            string data = await MemberViewContext.GetMembers(set, qexpr, prevlast);
            return Json(data);
        }

        [HttpGet]
        public ActionResult MemberDetails()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> MemberDetailsJson(string id)
        {
            var data = await MemberViewContext.GetBriefMemberDetails(id);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Authorize]
        public ActionResult SearchGroupMessages()
        {
            ViewBag.AppName = Startup.App.Name;
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> GetGroupMessages(string set, string qexpr, string prevlast)
        {
            var hub = new SignalRHubs.NotificationHub();
            var msgs = await GroupChatViewContext.GetMessages(hub.HubIdentity, User.Identity.GetUserId(), set, qexpr, prevlast);
            return Json(msgs);
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> LoadGroupMessageDetails(string groupId, string msgId)
        {
            var hub = new SignalRHubs.NotificationHub();
            var msg = await GroupChatViewContext.LoadMessageDetails(hub.HubIdentity, groupId, User.Identity.GetUserId(), msgId);
            return Json(msg);
        }

        [HttpGet]
        [Authorize]
        public ActionResult SearchPrivateMessages()
        {
            ViewBag.AppName = Startup.App.Name;
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> GetPrivateMessages(string set, string qexpr, string prevlast)
        {
            var hub = new SignalRHubs.NotificationHub();
            var msgs = await PrivateChatViewContext.GetMessages(hub.HubIdentity, User.Identity.GetUserId(), set, qexpr, prevlast);
            return Json(msgs);
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> LoadPrivateMessageDetails(string msgId)
        {
            var hub = new SignalRHubs.NotificationHub();
            var msg = await PrivateChatViewContext.LoadMessageDetails(hub.HubIdentity, User.Identity.GetUserId(), msgId);
            return Json(msg);
        }
    }
}

WebApps/MemberAdmin/Controllers/RoleAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Threading;
using System.Security.Principal;
using Microsoft.IdentityModel;
//using Microsoft.IdentityModel.Claims;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using CryptoGateway.RDB.Data.MembershipPlus;
using Archymeta.Web.Security;
using Archymeta.Web.Security.Resources;
using Archymeta.Web.MembershipPlus.AppLayer;
using Archymeta.Web.MembershipPlus.AppLayer.Models;
using MemberAdminMvc5.Models;

namespace MemberAdminMvc5.Controllers
{
    [Authorize]
    public class RoleAdminController : BaseController
    {
#if !NO_SIGNALR
        private Microsoft.AspNet.SignalR.IHubContext NoticeContext
        {
            get
            {
                return Microsoft.AspNet.SignalR.GlobalHost.ConnectionManager.GetHubContext<SignalRHubs.NotificationHub>();
            }
        }
#endif

        [HttpGet]
        [Authorize(Roles = "Administrators")]
        public async Task<ActionResult> RoleAdmin()
        {
            ViewBag.AppName = Startup.App.Name;
            var rrs = await MemberRoleContext.LoadRoleSetRoots(User.Identity.GetUserId());
            ViewBag.AdminMaxPriority = rrs.adminMaxLevel;
            string roleids = "[";
            foreach (var rid in rrs.adminRoleIds)
                roleids += (roleids == "[" ? " " : ", ") + rid;
            roleids += " ]";
            ViewBag.AdminRoleIds = roleids;
            return View(rrs.roots);
        }

        [HttpPost]
        [Authorize(Roles = "Administrators")]
        public async Task<ActionResult> AddUserToRole(string uid, int rid)
        {
            var OpResult = await MemberRoleContext.AddUserToRole(User.Identity.GetUserId(), uid, rid);
            await HandleNotification(uid, OpResult);
            return Json(OpResult.Result);
        }

        [HttpPost]
        [Authorize(Roles = "Administrators")]
        public async Task<ActionResult> AdjustUserRoleLevel(string uid, int rid, int del)
        {
            var OpResult = await MemberRoleContext.AdjustUserRoleLevel(User.Identity.GetUserId(), uid, rid, del);
            await HandleNotification(uid, OpResult);
            return Json(OpResult.Result);
        }

        [HttpPost]
        [Authorize(Roles = "Administrators")]
        public async Task<ActionResult> RemoveUserFromRole(string uid, int rid)
        {
            var OpResult = await MemberRoleContext.RemoveUserFromRole(User.Identity.GetUserId(), uid, rid);
            await HandleNotification(uid, OpResult);
            return Json(OpResult.Result);
        }

        private async Task HandleNotification(string uid, OperationResult OpResult)
        {
            if (OpResult.notices != null)
            {
                var member = await NotificationContext.SetNotification(uid, OpResult.notices);
#if !NO_SIGNALR
                var nhub = new SignalRHubs.NotificationHub();
                var mbhub =(from d in member.ChangedMemberCallbacks where d.HubID == nhub.HubIdentity select d).SingleOrDefault();
                if (IsSignalREnabled && mbhub != null && mbhub.ConnectionID != null && !mbhub.IsDisconnected)
                {
                    var lcateg = await NotificationContext.GetRecentCategorized(uid, OpResult.notices, 1, 15);
                    List<dynamic> lmsg = new List<dynamic>();
                    foreach (var n in OpResult.notices)
                    {
                        lmsg.Add(new
                        {
                            title = n.Title,
                            msg = n.Message,
                            priority = n.Priority
                        });
                    }
                    List<dynamic> categs = new List<dynamic>();
                    foreach (var categ in lcateg)
                    {
                        string categ_name = NotificationContext.MapCategoryName(categ, member.AcceptLanguages);
                        List<dynamic> l = new List<dynamic>();
                        foreach (var n in categ.ChangedMemberNotifications)
                        {
                            l.Add(new
                            {
                                title = n.DistinctString,
                                msg = "",
                                priority = n.PriorityLevel
                            });
                        }
                        categs.Add(new
                        {
                            name = categ_name,
                            list = l.ToArray()
                        });
                    }
                    NoticeContext.Clients.Client(mbhub.ConnectionID).serverNotifications(1, lmsg.ToArray(), categs);
                }
#endif
            }
        }

        [HttpGet]
        [Authorize(Roles = "Administrators")]
        public async Task<ActionResult> LoadRoleSetRoots()
        {
            var result = await MemberRoleContext.LoadRoleSetRoots(User.Identity.GetUserId());
            ViewBag.AdminMaxPriority = result.adminMaxLevel;
            string roleids = "[";
            foreach (var rid in result.adminRoleIds)
                roleids += (roleids == "[" ? " " : ", ") + rid;
            roleids += " ]";
            ViewBag.AdminRoleIds = roleids;
            return Json(result);
        }

        [HttpPost]
        [Authorize(Roles = "Administrators")]
        public async Task<ActionResult> LoadRoleChildren(int pid)
        {
            return Json(await MemberRoleContext.LoadRoleChildren(User.Identity.GetUserId(), pid));
        }

        [HttpPost]
        [Authorize(Roles = "Administrators")]
        public async Task<ActionResult> CreateNewRole(string name, int priority, int? pid)
        {
            return Json(await MemberRoleContext.CreateNewRole(User.Identity.GetUserId(), name, priority, pid));
        }

        [HttpPost]
        [Authorize(Roles = "Administrators")]
        public async Task<ActionResult> UpdateRole(int id, int priority, int? pid)
        {
            return Json(await MemberRoleContext.UpdateRole(User.Identity.GetUserId(), id, priority, pid));
        }

        [HttpPost]
        [Authorize(Roles = "Administrators")]
        public async Task<ActionResult> DeleteRole(int id)
        {
            return Json(await MemberRoleContext.DeleteRole(User.Identity.GetUserId(), id));
        }

        [HttpPost]
        [Authorize(Roles = "Administrators")]
        public async Task<ActionResult> ListUsersInRole(int id)
        {
            return Json(await MemberRoleContext.ListUsersInRole(User.Identity.GetUserId(), id));
        }
    }
}

WebApps/MemberAdmin/Views/Shared/_Layout.cshtml
@using Archymeta.Web.Security.Resources
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @ResourceUtils.GetString("2b5ca6c9ca99b01ad5c5b2ca6ac7ec71", "Membership+ Administration System")</title>
    @RenderSection("prestyles", required: false)
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/qtip2")
    @Styles.Render("~/Content/jgrowl")
    @RenderSection("styles", required: false)
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/ionicons")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        @Html.Partial("_TopbarPartial")
    </div>
    <div class="body-container body-content">
        @RenderBody()
    </div>
    <div class="container">
        <footer class="footer">
            <p style="text-align:center;">
                &copy; @DateTime.Now.Year - @Html.Raw(ResourceUtils.GetString("5eab1b11c48a0f997c644f3162d9c2c7", @"<a href=""http://www.archymeta.com"">Archymeta Information Techenologies Co., Ltd.</a>, All rights reserved"))
            </p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/qtip")
    @Scripts.Render("~/bundles/jgrowl")
    @if (Request.IsAuthenticated)
    {
        Html.RenderAction("GetSystemNotificationWrapper", "Home");
    }
    @RenderSection("scripts", required: false)
</body>
</html>

WebApps/MemberAdmin/Views/Shared/_QueryComposerPartial.cshtml
@using Archymeta.Web.Security.Resources;
<div class="QueryInput">
    <table>
        <tbody>
            <tr>
                <td>
                    <label for="sortOpts">@ResourceUtils.GetString("6549f41e489efc896d2ce1e7a3e7df98", "Sorted by:")</label>
                </td>
                <td class="sorterexpr">
                    <div class="sortnode">&nbsp;</div>
                    <!-- ko foreach: SorterPath -->
                    <!-- ko ifnot: IsExternal || DisplayAs == "this" -->
                    <div class="sortnode" data-bind="text: DisplayAs">
                    </div>
                    <!-- ko if: IsEntityAccess -->
                    <div class="dotnode">
                        <img src="@Url.Content("~/Images/node_green.png")" alt="." />
                    </div>
                    <!-- /ko -->
                    <!-- /ko -->
                    <!-- ko ifnot:IsExternal || DisplayAs != "this" -->
                    <div class="thisnode" data-bind="text: DisplayAs">
                    </div>
                    <!-- ko if: IsEntityAccess -->
                    <div class="dotnode">
                        <img src="@Url.Content("~/Images/node_green.png")" alt="." />
                    </div>
                    <!-- /ko -->
                    <!-- /ko -->
                    <!-- ko if: IsExternal -->
                    <div class="dirnode">
                        <span data-bind="attr: { class: ImgSrc, title: DisplayAs }" />
                        @*<img data-bind="attr: {src: ImgSrc, alt: DisplayAs, title: DisplayAs}" />*@
                    </div>
                    <!-- /ko -->
                    <!-- /ko -->
                    <input id="sortOpts" />
                </td>
            </tr>
            <tr>
                <td>
                    <label for="filterOpts">@ResourceUtils.GetString("9bc9d2baa9a21cb5c8336f12260a2190", "Filtered by:")</label>
                </td>
                <td class="filterexpr">
                    <div class="filternode">&nbsp;</div>
                    <!-- ko foreach: FilterPath -->
                    <div data-bind="text: DisplayAs, css: TkClass">
                    </div>
                    <!-- /ko -->
                    <input id="filterOpts" />
                </td>
            </tr>
            <tr>
                <td><label>@ResourceUtils.GetString("aafc06e1c4ee34e108c35f226456bea1", "which means:")</label></td>
                <td class="filterexpr">
                    <p>
                        <!-- ko if: CurrentFilters() != null -->
                        <span data-bind="text: CurrentFilters().CurrentExpr "></span>
                        <!-- /ko -->
                    </p>
                </td>
            </tr>
        </tbody>
    </table>
</div>

WebApps/MemberAdmin/Views/Shared/_TopbarPartial.cshtml
@using Archymeta.Web.Security.Resources
<div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        @Html.ActionLink("+", "Index", "Home", null, new { @class = "navbar-brand ion-android-social" })
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink(ResourceUtils.GetString("8cf04a9734132302f96da8e113e80ce6", "Home"), "Index", "Home")</li>
            @if (Request.IsAuthenticated)
            {
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">@ResourceUtils.GetString("77a3f553666ab77020a502e5079335c9", "Membership")<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li class="dropdown-submenu">
                            <a href="#">@ResourceUtils.GetString("13348442cc6a27032d2b4aa28b75a5d4", "Search")</a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink(ResourceUtils.GetString("ef53538ae41a651c7f72ab6cb1135d8d", "Members"), "SearchMembers", "Query")</li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">@ResourceUtils.GetString("07a3dd247ad6bec7fe401aa1161995a0", "Communication")<b class="caret"></b></a>
                    <ul class="dropdown-menu" role="menu">
                        <li class="dropdown-submenu">
                            <a href="#">@ResourceUtils.GetString("b54fa74b22da5a748eae3d55ad26419a", "Messaging")</a>
                            <ul class="dropdown-menu" role="menu">
                                <li class="dropdown-submenu">
                                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">@ResourceUtils.GetString("c41bd4a897a72c15332aa063685bf0a2", "Group Chat")</a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li>@Html.ActionLink(ResourceUtils.GetString("63b688de6ab7645387cb12b6e596b85c", "Chat Groups"), "Start", "GroupChat")</li>
                                        <li>@Html.ActionLink(ResourceUtils.GetString("5d5d7ec6e0b614e9d21f38d06ac90123", "Dialogues & Messages"), "PrevMessages", "GroupPrivateChat")</li>
                                        <li>@Html.ActionLink(ResourceUtils.GetString("13348442cc6a27032d2b4aa28b75a5d4", "Search"), "SearchGroupMessages", "Query")</li>
                                    </ul>
                                </li>
                                <li class="dropdown-submenu">
                                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">@ResourceUtils.GetString("e9b58070003826eb74265c9ff2815e81", "Private Chat")</a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li>@Html.ActionLink(ResourceUtils.GetString("8dff9be37a347cab463edab00c45f32a", "Search Online Members"), "Search", "PrivateChat")</li>
                                        <li>@Html.ActionLink(ResourceUtils.GetString("f61f233079fec6bd451747c6cdaeb1c7", "Search Contacts"), "Search", "Contacts")</li>
                                        <li>@Html.ActionLink(ResourceUtils.GetString("5d5d7ec6e0b614e9d21f38d06ac90123", "Dialogues & Messages"), "UnreadMessages", "PrivateChat")</li>
                                        <li>@Html.ActionLink(ResourceUtils.GetString("13348442cc6a27032d2b4aa28b75a5d4", "Search"), "SearchPrivateMessages", "Query")</li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">@ResourceUtils.GetString("184daff620aca4ad23fd2bf70d0b76b0", "Personal")<b class="caret"></b></a>
                    <ul class="dropdown-menu" role="menu">
                        <li class="dropdown-submenu">
                            <a href="#">@ResourceUtils.GetString("f4f70727dc34561dfde1a3c529b6205d", "Settings")</a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink(ResourceUtils.GetString("fe7fc019efd9d8c63caa40b65a987050", "Change account info"), "ChangeAccountInfo", "Account")</li>
                                <li>@Html.ActionLink(ResourceUtils.GetString("19ea043ac4635abf9e611b26e847eda2", "Maintain profile"), "UserDetails", "Account")</li>
                            </ul>
                        </li>
                        <li class="dropdown-submenu">
                            <a href="#">@ResourceUtils.GetString("a82be0f551b8708bc08eb33cd9ded0d0", "Information")</a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink(ResourceUtils.GetString("a274f4d4670213a9045ce258c6c56b81", "Notifications"), "", "Notification")</li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle">@ResourceUtils.GetString("e3afed0047b08059d0fada10f400c1e6", "Admin")<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink(ResourceUtils.GetString("f9aae5fda8d810a29f12d1e61b4ab260", "Users"), "UserAdmin", "MemberAdmin")</li>
                        <li>@Html.ActionLink(ResourceUtils.GetString("a5cd3ed116608dac017f14c046ea56c0", "Roles"), "RoleAdmin", "RoleAdmin")</li>
                        <li class="dropdown-submenu">
                            <a href="#">@ResourceUtils.GetString("c33e404a441c6ba9648f88af3c68a1cb", "Statistics")</a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink(ResourceUtils.GetString("6252099885d35731bcdb935fb4582e7a", "Online Users"), "OnlineUsers", "MemberAdmin")</li>
                            </ul>
                        </li>
                    </ul>
                </li>
            }
            <li>@Html.ActionLink(ResourceUtils.GetString("bbaff12800505b22a853e8b7f4eb6a23", "Contact"), "Contact", "Home")</li>
            <li>@Html.ActionLink(ResourceUtils.GetString("8f7f4c1ce7a4f933663d10543562b097", "About"), "About", "Home")</li>
        </ul>
        @Html.Partial("_LoginPartial")
    </div>
</div>